import { Routes } from '@angular/router';
import { DashboardPageComponent } from './pages/dashboard-page';
import { FinancePageComponent } from './pages/finance-page';
import { OrdersPageComponent } from './pages/orders-page';
import { ProductsPageComponent } from './pages/products-page';
import { SettingsPageComponent } from './pages/settings-page';

import { GenelMuhasebeComponent } from './pages/erp/finans/genel-muhasebe.component';
import { AlacaklarComponent } from './pages/erp/finans/alacaklar.component';
import { BorclarComponent } from './pages/erp/finans/borclar.component';
import { ButceYonetimiComponent } from './pages/erp/finans/butce-yonetimi.component';
import { SabitKiymetlerComponent } from './pages/erp/finans/sabit-kiymetler.component';
import { SatisYonetimiComponent } from './pages/erp/satis/satis-yonetimi.component';
import { CrmComponent } from './pages/erp/satis/crm.component';
import { TeklifSiparisComponent } from './pages/erp/satis/teklif-siparis.component';
import { KampanyaYonetimiComponent } from './pages/erp/satis/kampanya-yonetimi.component';
import { TedarikciYonetimiComponent } from './pages/erp/satinalma/tedarikci-yonetimi.component';
import { SatinalmaTaleplerComponent } from './pages/erp/satinalma/satinalma-talepler.component';
import { SatinalmaSiparislerComponent } from './pages/erp/satinalma/satinalma-siparisler.component';
import { FiyatSozlesmeComponent } from './pages/erp/satinalma/fiyat-sozlesme.component';
import { EnvanterTakibiComponent } from './pages/erp/stok/envanter-takibi.component';
import { DepoYonetimiComponent } from './pages/erp/stok/depo-yonetimi.component';
import { LojistikSevkiyatComponent } from './pages/erp/stok/lojistik-sevkiyat.component';
import { UretimPlanlamaComponent } from './pages/erp/uretim/uretim-planlama.component';
import { IsEmirleriComponent } from './pages/erp/uretim/is-emirleri.component';
import { KaliteKontrolComponent } from './pages/erp/uretim/kalite-kontrol.component';
import { PersonelYonetimiComponent } from './pages/erp/ik/personel-yonetimi.component';
import { BordroComponent } from './pages/erp/ik/bordro.component';
import { IzinMesaiComponent } from './pages/erp/ik/izin-mesai.component';
import { ProjePlanlamaComponent } from './pages/erp/proje/proje-planlama.component';
import { KaynakYonetimiComponent } from './pages/erp/proje/kaynak-yonetimi.component';
import { TeknikServisComponent } from './pages/erp/bakim/teknik-servis.component';
import { ArizaTakibiComponent } from './pages/erp/bakim/ariza-takibi.component';
import { OnlineSiparisComponent } from './pages/erp/eticaret/online-siparis.component';
import { KpiTakibiComponent } from './pages/erp/analitik/kpi-takibi.component';
import { YetkilendirmeComponent } from './pages/erp/uyum/yetkilendirme.component';
import { DenetimIzleriComponent } from './pages/erp/uyum/denetim-izleri.component';

import { BelgeArsivlemeComponent } from './pages/erp/dokuman/belge-arsivleme.component';
import { VersiyonKontrolComponent } from './pages/erp/dokuman/versiyon-kontrol.component';
import { ElektronikImzaComponent } from './pages/erp/dokuman/elektronik-imza.component';
import { IsoUyumComponent } from './pages/erp/kalite/iso-uyum.component';
import { DenetimSertifikasyonComponent } from './pages/erp/kalite/denetim-sertifikasyon.component';
import { SurekliIyilestirmeComponent } from './pages/erp/kalite/surekli-iyilestirme.component';
import { IsSagligiGuvenligiComponent } from './pages/erp/ehs/is-sagligi-guvenligi.component';
import { CevreselEtkiComponent } from './pages/erp/ehs/cevresel-etki.component';
import { RiskYonetimiComponent } from './pages/erp/ehs/risk-yonetimi.component';
import { UrunTasarimiComponent } from './pages/erp/plm/urun-tasarimi.component';
import { PlmVersiyonlamaComponent } from './pages/erp/plm/versiyonlama.component';
import { UrunGelistirmeComponent } from './pages/erp/plm/urun-gelistirme.component';
import { TalepTahminiComponent } from './pages/erp/scm/talep-tahmini.component';
import { LojistikOptimizasyonComponent } from './pages/erp/scm/lojistik-optimizasyon.component';
import { TedarikciPerformansComponent } from './pages/erp/scm/tedarikci-performans.component';
import { CagriMerkeziComponent } from './pages/erp/musteri-destek/cagri-merkezi.component';
import { TicketYonetimiComponent } from './pages/erp/musteri-destek/ticket-yonetimi.component';
import { ChatbotAiComponent } from './pages/erp/musteri-destek/chatbot-ai.component';
import { EFaturaComponent } from './pages/erp/efatura/e-fatura.component';
import { EArsivComponent } from './pages/erp/efatura/e-arsiv.component';
import { EIrsaliyeComponent } from './pages/erp/efatura/e-irsaliye.component';
import { EMutabakatComponent } from './pages/erp/efatura/e-mutabakat.component';
import { OnlineBankaComponent } from './pages/erp/odeme/online-banka.component';
import { SanalPosComponent } from './pages/erp/odeme/sanal-pos.component';
import { OtomatikTahsilatComponent } from './pages/erp/odeme/otomatik-tahsilat.component';
import { CalisanEgitimiComponent } from './pages/erp/lms/calisan-egitimi.component';
import { SertifikaTakibiComponent } from './pages/erp/lms/sertifika-takibi.component';
import { OnlineEgitimComponent } from './pages/erp/lms/online-egitim.component';
import { OneriSistemiComponent } from './pages/erp/inovasyon/oneri-sistemi.component';
import { InovasyonProjeleriComponent } from './pages/erp/inovasyon/inovasyon-projeleri.component';
import { DegerlendirmeOdullendirmeComponent } from './pages/erp/inovasyon/degerlendirme-odullendirme.component';

import { VeriMadenciligiComponent } from './pages/erp/is-zekasi/veri-madenciligi.component';
import { RaporlamaBiComponent } from './pages/erp/is-zekasi/raporlama-bi.component';
import { MobilErpYonetimiComponent } from './pages/erp/mobil-erp/mobil-erp-yonetimi.component';
import { MobilOnayComponent } from './pages/erp/mobil-erp/mobil-onay.component';
import { CokParaBirimiComponent } from './pages/erp/uluslararasi/cok-para-birimi.component';
import { VergiUyumComponent } from './pages/erp/uluslararasi/vergi-uyum.component';
import { SadakatProgramiComponent } from './pages/erp/sadakat/sadakat-programi.component';
import { KampanyaYonetimiSadakatComponent } from './pages/erp/sadakat/kampanya-yonetimi-sadakat.component';
import { TedarikciPortalComponent } from './pages/erp/tedarikci-portal/tedarikci-portal.component';
import { TedarikciTekliflerComponent } from './pages/erp/tedarikci-portal/tedarikci-teklifler.component';
import { UretimCizelgeComponent } from './pages/erp/aps/uretim-cizelge.component';
import { KapasitePlanlamaComponent } from './pages/erp/aps/kapasite-planlama.component';
import { RiskDegerlendirmeComponent } from './pages/erp/risk-sigorta/risk-degerlendirme.component';
import { SigortaYonetimiComponent } from './pages/erp/risk-sigorta/sigorta-yonetimi.component';
import { EnerjiTuketimiComponent } from './pages/erp/enerji/enerji-tuketimi.component';
import { KaynakOptimizasyonComponent } from './pages/erp/enerji/kaynak-optimizasyon.component';
import { SozlesmeYonetimiComponent } from './pages/erp/hukuk/sozlesme-yonetimi.component';
import { HukukiDavalarComponent } from './pages/erp/hukuk/hukuki-davalar.component';
import { StartupPortfoyComponent } from './pages/erp/inovasyon-startup/startup-portfoy.component';
import { ArGeYonetimiComponent } from './pages/erp/inovasyon-startup/ar-ge-yonetimi.component';
import { SosyalMedyaErpComponent } from './pages/erp/sosyal-erp/sosyal-medya-erp.component';
import { CalismAkisiComponent } from './pages/erp/sosyal-erp/calisma-akisi.component';
import { AiTahminlemeComponent } from './pages/erp/ai-erp/ai-tahminleme.component';
import { AiOptimizasyonComponent } from './pages/erp/ai-erp/ai-optimizasyon.component';
import { UxAnalitikComponent } from './pages/erp/musteri-ux/ux-analitik.component';
import { DeneyimHaritasiComponent } from './pages/erp/musteri-ux/deneyim-haritasi.component';
import { IotCihazlarComponent } from './pages/erp/iot/iot-cihazlar.component';
import { SensorVeriComponent } from './pages/erp/iot/sensor-veri.component';
import { MlModellerComponent } from './pages/erp/ai-ml/ml-modeller.component';
import { VeriEtiketlemeComponent } from './pages/erp/ai-ml/veri-etiketleme.component';
import { AkilliSozlesmelerComponent } from './pages/erp/blockchain/akilli-sozlesmeler.component';
import { DijitalVarlikComponent } from './pages/erp/blockchain/dijital-varlik.component';
import { MusteriPortalComponent } from './pages/erp/musteri-portal/musteri-portal.component';
import { SelfServisComponent } from './pages/erp/musteri-portal/self-servis.component';
import { SatisSonrasiServisComponent } from './pages/erp/satis-sonrasi/satis-sonrasi-servis.component';
import { YedekParcaComponent } from './pages/erp/satis-sonrasi/yedek-parca.component';
import { DijitalKampanyaComponent } from './pages/erp/dijital-pazarlama/dijital-kampanya.component';
import { SosyalMedyaDpComponent } from './pages/erp/dijital-pazarlama/sosyal-medya-dp.component';
import { KvkkUyumComponent } from './pages/erp/veri-guvenligi/kvkk-uyum.component';
import { VeriSiniflandirmaComponent } from './pages/erp/veri-guvenligi/veri-siniflandirma.component';
import { BpmSurecComponent } from './pages/erp/bpm/bpm-surec.component';
import { OtomasyonIzlemeComponent } from './pages/erp/bpm/otomasyon-izleme.component';
import { SektorModulComponent } from './pages/erp/sektörel/sektor-modul.component';
import { InsaatModuluComponent } from './pages/erp/sektörel/insaat-modulu.component';
import { TalepTahminAiComponent } from './pages/erp/ai-tahmin/talep-tahmin-ai.component';
import { FiyatTahminComponent } from './pages/erp/ai-tahmin/fiyat-tahmin.component';
import { DijitalIkizSimComponent } from './pages/erp/dijital-ikiz/dijital-ikiz-sim.component';
import { UrunIkizComponent } from './pages/erp/dijital-ikiz/urun-ikiz.component';
import { EsgRaporComponent } from './pages/erp/esg/esg-rapor.component';
import { KarbonAyakIziComponent } from './pages/erp/esg/karbon-ayak-izi.component';
import { RpaBotlarComponent } from './pages/erp/rpa/rpa-botlar.component';
import { RpaSurecleriComponent } from './pages/erp/rpa/rpa-surecleri.component';
import { OmniKanalComponent } from './pages/erp/omni-channel/omni-kanal.component';
import { SiparisYonetimiOmniComponent } from './pages/erp/omni-channel/siparis-yonetimi-omni.component';
import { AiHrYetenekComponent } from './pages/erp/ai-hr/ai-hr-yetenek.component';
import { PerformansAiComponent } from './pages/erp/ai-hr/performans-ai.component';
import { FiloYonetimiComponent } from './pages/erp/akilli-lojistik/filo-yonetimi.component';
import { RotaOptimizasyonComponent } from './pages/erp/akilli-lojistik/rota-optimizasyon.component';
import { BankaEntegrasyonComponent } from './pages/erp/dijital-bankacilik/banka-entegrasyon.component';
import { OdemeAgGecigiComponent } from './pages/erp/dijital-bankacilik/odeme-ag-gecigi.component';
import { KamuIhaleComponent } from './pages/erp/kamu-regulasyon/kamu-ihale.component';
import { RegulasyonUyumComponent } from './pages/erp/kamu-regulasyon/regulasyon-uyum.component';
import { AkilliFabrikaComponent } from './pages/erp/endustri40/akilli-fabrika.component';
import { CobotlarComponent } from './pages/erp/endustri40/cobotlar.component';
import { GonullularComponent } from './pages/erp/csr/gonulluler.component';
import { BagisYonetimiComponent } from './pages/erp/csr/bagis-yonetimi.component';
import { EgitimPlatformComponent } from './pages/erp/egitim-inovasyon/egitim-platform.component';
import { GamificationComponent } from './pages/erp/egitim-inovasyon/gamification.component';
import { AiSatisTahminiComponent } from './pages/erp/ai-satis/ai-satis-tahmini.component';
import { MusteriSkorlamaComponent } from './pages/erp/ai-satis/musteri-skorlama.component';
import { VrEgitimComponent } from './pages/erp/vr-ar/vr-egitim.component';
import { ArBakimComponent } from './pages/erp/vr-ar/ar-bakim.component';
import { TehditMerkeziComponent } from './pages/erp/siber-guvenlik/tehdit-merkezi.component';
import { GuvenlikOlaylariComponent } from './pages/erp/siber-guvenlik/guvenlik-olaylari.component';
import { IsbirligiAraclariComponent } from './pages/erp/dijital-iletisim/isbirligi-araclari.component';
import { VideoKonferansComponent } from './pages/erp/dijital-iletisim/video-konferans.component';
import { EnerjiPanelComponent } from './pages/erp/akilli-enerji/enerji-panel.component';
import { SariYonetimiComponent } from './pages/erp/akilli-enerji/sari-yonetimi.component';
import { GumrukBeyanComponent } from './pages/erp/gumruk/gumruk-beyan.component';
import { IthalatIhracatComponent } from './pages/erp/gumruk/ithalat-ihracat.component';
import { ChatbotMusteriComponent } from './pages/erp/ai-musteri/chatbot-musteri.component';
import { DuyguAnaliziComponent } from './pages/erp/ai-musteri/duygu-analizi.component';
import { SaglikTakipComponent } from './pages/erp/dijital-saglik/saglik-takip.component';
import { WellbeingProgramiComponent } from './pages/erp/dijital-saglik/wellbeing-programi.component';
import { TarimAraziComponent } from './pages/erp/tarim-erp/tarim-arazi.component';
import { HasatPlanlamaComponent } from './pages/erp/tarim-erp/hasat-planlama.component';
import { SehirHizmetleriComponent } from './pages/erp/akilli-sehir/sehir-hizmetleri.component';
import { AltyapiYonetimiComponent } from './pages/erp/akilli-sehir/altyapi-yonetimi.component';
import { KriptoFintechComponent } from './pages/erp/fintech/kripto-fintech.component';
import { MikroFinansComponent } from './pages/erp/fintech/mikro-finans.component';
import { EtkinlikYonetimiComponent } from './pages/erp/kultur-sanat/etkinlik-yonetimi.component';
import { KoleksiyonYonetimiComponent } from './pages/erp/kultur-sanat/koleksiyon-yonetimi.component';
import { UyeFitnessComponent } from './pages/erp/spor-fitness/uye-fitness.component';
import { AntreymanPlaniComponent } from './pages/erp/spor-fitness/antreyman-plani.component';
import { RezervasyonComponent } from './pages/erp/turizm/rezervasyon.component';
import { OdaYonetimiComponent } from './pages/erp/turizm/oda-yonetimi.component';
import { UcusYonetimiComponent } from './pages/erp/havacilik/ucus-yonetimi.component';
import { BakimPlanlamaHavacComponent } from './pages/erp/havacilik/bakim-planlama-havac.component';
import { ArsaTakipComponent } from './pages/erp/arsa-tarla/arsa-takip.component';
import { TapuIslemleriComponent } from './pages/erp/arsa-tarla/tapu-islemleri.component';
import { DemirbaslarComponent } from './pages/erp/demirbaslar/demirbaslar.component';
import { ZimmetComponent } from './pages/erp/demirbaslar/zimmet.component';
import { AmortismanComponent } from './pages/erp/demirbaslar/amortisman.component';
import { HayvanTakipComponent } from './pages/erp/hayvancilik/hayvan-takip.component';
import { YemYonetimiComponent } from './pages/erp/hayvancilik/yem-yonetimi.component';
import { SaglikAsiComponent } from './pages/erp/hayvancilik/saglik-asi.component';

export const routes: Routes = [
	{ path: '', pathMatch: 'full', redirectTo: 'dashboard' },
	{ path: 'dashboard', component: DashboardPageComponent },
	{ path: 'urunler', component: ProductsPageComponent },
	{ path: 'siparisler', component: OrdersPageComponent },
	{ path: 'finans', component: FinancePageComponent },
	{ path: 'ayarlar', component: SettingsPageComponent },
	{ path: 'erp/finans/genel-muhasebe', component: GenelMuhasebeComponent },
	{ path: 'erp/finans/alacaklar', component: AlacaklarComponent },
	{ path: 'erp/finans/borclar', component: BorclarComponent },
	{ path: 'erp/finans/butce-yonetimi', component: ButceYonetimiComponent },
	{ path: 'erp/finans/sabit-kiymetler', component: SabitKiymetlerComponent },
	{ path: 'erp/satis/satis-yonetimi', component: SatisYonetimiComponent },
	{ path: 'erp/satis/crm', component: CrmComponent },
	{ path: 'erp/satis/teklif-siparis', component: TeklifSiparisComponent },
	{ path: 'erp/satis/kampanya-yonetimi', component: KampanyaYonetimiComponent },
	{ path: 'erp/satinalma/tedarikci-yonetimi', component: TedarikciYonetimiComponent },
	{ path: 'erp/satinalma/satinalma-talepler', component: SatinalmaTaleplerComponent },
	{ path: 'erp/satinalma/satinalma-siparisler', component: SatinalmaSiparislerComponent },
	{ path: 'erp/satinalma/fiyat-sozlesme', component: FiyatSozlesmeComponent },
	{ path: 'erp/stok/envanter-takibi', component: EnvanterTakibiComponent },
	{ path: 'erp/stok/depo-yonetimi', component: DepoYonetimiComponent },
	{ path: 'erp/stok/lojistik-sevkiyat', component: LojistikSevkiyatComponent },
	{ path: 'erp/uretim/uretim-planlama', component: UretimPlanlamaComponent },
	{ path: 'erp/uretim/is-emirleri', component: IsEmirleriComponent },
	{ path: 'erp/uretim/kalite-kontrol', component: KaliteKontrolComponent },
	{ path: 'erp/ik/personel-yonetimi', component: PersonelYonetimiComponent },
	{ path: 'erp/ik/bordro', component: BordroComponent },
	{ path: 'erp/ik/izin-mesai', component: IzinMesaiComponent },
	{ path: 'erp/proje/proje-planlama', component: ProjePlanlamaComponent },
	{ path: 'erp/proje/kaynak-yonetimi', component: KaynakYonetimiComponent },
	{ path: 'erp/bakim/teknik-servis', component: TeknikServisComponent },
	{ path: 'erp/bakim/ariza-takibi', component: ArizaTakibiComponent },
	{ path: 'erp/eticaret/online-siparis', component: OnlineSiparisComponent },
	{ path: 'erp/analitik/kpi-takibi', component: KpiTakibiComponent },
	{ path: 'erp/uyum/yetkilendirme', component: YetkilendirmeComponent },
	{ path: 'erp/uyum/denetim-izleri', component: DenetimIzleriComponent },
	{ path: 'erp/dokuman/belge-arsivleme', component: BelgeArsivlemeComponent },
	{ path: 'erp/dokuman/versiyon-kontrol', component: VersiyonKontrolComponent },
	{ path: 'erp/dokuman/elektronik-imza', component: ElektronikImzaComponent },
	{ path: 'erp/kalite/iso-uyum', component: IsoUyumComponent },
	{ path: 'erp/kalite/denetim-sertifikasyon', component: DenetimSertifikasyonComponent },
	{ path: 'erp/kalite/surekli-iyilestirme', component: SurekliIyilestirmeComponent },
	{ path: 'erp/ehs/is-sagligi-guvenligi', component: IsSagligiGuvenligiComponent },
	{ path: 'erp/ehs/cevresel-etki', component: CevreselEtkiComponent },
	{ path: 'erp/ehs/risk-yonetimi', component: RiskYonetimiComponent },
	{ path: 'erp/plm/urun-tasarimi', component: UrunTasarimiComponent },
	{ path: 'erp/plm/versiyonlama', component: PlmVersiyonlamaComponent },
	{ path: 'erp/plm/urun-gelistirme', component: UrunGelistirmeComponent },
	{ path: 'erp/scm/talep-tahmini', component: TalepTahminiComponent },
	{ path: 'erp/scm/lojistik-optimizasyon', component: LojistikOptimizasyonComponent },
	{ path: 'erp/scm/tedarikci-performans', component: TedarikciPerformansComponent },
	{ path: 'erp/musteri-destek/cagri-merkezi', component: CagriMerkeziComponent },
	{ path: 'erp/musteri-destek/ticket-yonetimi', component: TicketYonetimiComponent },
	{ path: 'erp/musteri-destek/chatbot-ai', component: ChatbotAiComponent },
	{ path: 'erp/efatura/e-fatura', component: EFaturaComponent },
	{ path: 'erp/efatura/e-arsiv', component: EArsivComponent },
	{ path: 'erp/efatura/e-irsaliye', component: EIrsaliyeComponent },
	{ path: 'erp/efatura/e-mutabakat', component: EMutabakatComponent },
	{ path: 'erp/odeme/online-banka', component: OnlineBankaComponent },
	{ path: 'erp/odeme/sanal-pos', component: SanalPosComponent },
	{ path: 'erp/odeme/otomatik-tahsilat', component: OtomatikTahsilatComponent },
	{ path: 'erp/lms/calisan-egitimi', component: CalisanEgitimiComponent },
	{ path: 'erp/lms/sertifika-takibi', component: SertifikaTakibiComponent },
	{ path: 'erp/lms/online-egitim', component: OnlineEgitimComponent },
	{ path: 'erp/inovasyon/oneri-sistemi', component: OneriSistemiComponent },
	{ path: 'erp/inovasyon/inovasyon-projeleri', component: InovasyonProjeleriComponent },
	{ path: 'erp/inovasyon/degerlendirme-odullendirme', component: DegerlendirmeOdullendirmeComponent },
	{ path: 'erp/is-zekasi/veri-madenciligi', component: VeriMadenciligiComponent },
	{ path: 'erp/is-zekasi/raporlama-bi', component: RaporlamaBiComponent },
	{ path: 'erp/mobil-erp/mobil-erp-yonetimi', component: MobilErpYonetimiComponent },
	{ path: 'erp/mobil-erp/mobil-onay', component: MobilOnayComponent },
	{ path: 'erp/uluslararasi/cok-para-birimi', component: CokParaBirimiComponent },
	{ path: 'erp/uluslararasi/vergi-uyum', component: VergiUyumComponent },
	{ path: 'erp/sadakat/sadakat-programi', component: SadakatProgramiComponent },
	{ path: 'erp/sadakat/kampanya-yonetimi', component: KampanyaYonetimiSadakatComponent },
	{ path: 'erp/tedarikci-portal/tedarikci-portal', component: TedarikciPortalComponent },
	{ path: 'erp/tedarikci-portal/tedarikci-teklifler', component: TedarikciTekliflerComponent },
	{ path: 'erp/aps/uretim-cizelge', component: UretimCizelgeComponent },
	{ path: 'erp/aps/kapasite-planlama', component: KapasitePlanlamaComponent },
	{ path: 'erp/risk-sigorta/risk-degerlendirme', component: RiskDegerlendirmeComponent },
	{ path: 'erp/risk-sigorta/sigorta-yonetimi', component: SigortaYonetimiComponent },
	{ path: 'erp/enerji/enerji-tuketimi', component: EnerjiTuketimiComponent },
	{ path: 'erp/enerji/kaynak-optimizasyon', component: KaynakOptimizasyonComponent },
	{ path: 'erp/hukuk/sozlesme-yonetimi', component: SozlesmeYonetimiComponent },
	{ path: 'erp/hukuk/hukuki-davalar', component: HukukiDavalarComponent },
	{ path: 'erp/inovasyon-startup/startup-portfoy', component: StartupPortfoyComponent },
	{ path: 'erp/inovasyon-startup/ar-ge-yonetimi', component: ArGeYonetimiComponent },
	{ path: 'erp/sosyal-erp/sosyal-medya', component: SosyalMedyaErpComponent },
	{ path: 'erp/sosyal-erp/calisma-akisi', component: CalismAkisiComponent },
	{ path: 'erp/ai-erp/ai-tahminleme', component: AiTahminlemeComponent },
	{ path: 'erp/ai-erp/ai-optimizasyon', component: AiOptimizasyonComponent },
	{ path: 'erp/musteri-ux/ux-analitik', component: UxAnalitikComponent },
	{ path: 'erp/musteri-ux/deneyim-haritasi', component: DeneyimHaritasiComponent },
	{ path: 'erp/iot/iot-cihazlar', component: IotCihazlarComponent },
	{ path: 'erp/iot/sensor-veri', component: SensorVeriComponent },
	{ path: 'erp/ai-ml/ml-modeller', component: MlModellerComponent },
	{ path: 'erp/ai-ml/veri-etiketleme', component: VeriEtiketlemeComponent },
	{ path: 'erp/blockchain/akilli-sozlesmeler', component: AkilliSozlesmelerComponent },
	{ path: 'erp/blockchain/dijital-varlik', component: DijitalVarlikComponent },
	{ path: 'erp/musteri-portal/musteri-portal', component: MusteriPortalComponent },
	{ path: 'erp/musteri-portal/self-servis', component: SelfServisComponent },
	{ path: 'erp/satis-sonrasi/satis-sonrasi-servis', component: SatisSonrasiServisComponent },
	{ path: 'erp/satis-sonrasi/yedek-parca', component: YedekParcaComponent },
	{ path: 'erp/dijital-pazarlama/dijital-kampanya', component: DijitalKampanyaComponent },
	{ path: 'erp/dijital-pazarlama/sosyal-medya', component: SosyalMedyaDpComponent },
	{ path: 'erp/veri-guvenligi/kvkk-uyum', component: KvkkUyumComponent },
	{ path: 'erp/veri-guvenligi/veri-siniflandirma', component: VeriSiniflandirmaComponent },
	{ path: 'erp/bpm/bpm-surec', component: BpmSurecComponent },
	{ path: 'erp/bpm/otomasyon-izleme', component: OtomasyonIzlemeComponent },
	{ path: 'erp/sektörel/sektor-modul', component: SektorModulComponent },
	{ path: 'erp/sektörel/insaat-modulu', component: InsaatModuluComponent },
	{ path: 'erp/ai-tahmin/talep-tahmin-ai', component: TalepTahminAiComponent },
	{ path: 'erp/ai-tahmin/fiyat-tahmin', component: FiyatTahminComponent },
	{ path: 'erp/dijital-ikiz/dijital-ikiz-sim', component: DijitalIkizSimComponent },
	{ path: 'erp/dijital-ikiz/urun-ikiz', component: UrunIkizComponent },
	{ path: 'erp/esg/esg-rapor', component: EsgRaporComponent },
	{ path: 'erp/esg/karbon-ayak-izi', component: KarbonAyakIziComponent },
	{ path: 'erp/rpa/rpa-botlar', component: RpaBotlarComponent },
	{ path: 'erp/rpa/rpa-surecleri', component: RpaSurecleriComponent },
	{ path: 'erp/omni-channel/omni-kanal', component: OmniKanalComponent },
	{ path: 'erp/omni-channel/siparis-yonetimi', component: SiparisYonetimiOmniComponent },
	{ path: 'erp/ai-hr/ai-hr-yetenek', component: AiHrYetenekComponent },
	{ path: 'erp/ai-hr/performans-ai', component: PerformansAiComponent },
	{ path: 'erp/akilli-lojistik/filo-yonetimi', component: FiloYonetimiComponent },
	{ path: 'erp/akilli-lojistik/rota-optimizasyon', component: RotaOptimizasyonComponent },
	{ path: 'erp/dijital-bankacilik/banka-entegrasyon', component: BankaEntegrasyonComponent },
	{ path: 'erp/dijital-bankacilik/odeme-ag-gecigi', component: OdemeAgGecigiComponent },
	{ path: 'erp/kamu-regulasyon/kamu-ihale', component: KamuIhaleComponent },
	{ path: 'erp/kamu-regulasyon/regulasyon-uyum', component: RegulasyonUyumComponent },
	{ path: 'erp/endustri40/akilli-fabrika', component: AkilliFabrikaComponent },
	{ path: 'erp/endustri40/cobotlar', component: CobotlarComponent },
	{ path: 'erp/csr/gonulluler', component: GonullularComponent },
	{ path: 'erp/csr/bagis-yonetimi', component: BagisYonetimiComponent },
	{ path: 'erp/egitim-inovasyon/egitim-platform', component: EgitimPlatformComponent },
	{ path: 'erp/egitim-inovasyon/gamification', component: GamificationComponent },
	{ path: 'erp/ai-satis/ai-satis-tahmini', component: AiSatisTahminiComponent },
	{ path: 'erp/ai-satis/musteri-skorlama', component: MusteriSkorlamaComponent },
	{ path: 'erp/vr-ar/vr-egitim', component: VrEgitimComponent },
	{ path: 'erp/vr-ar/ar-bakim', component: ArBakimComponent },
	{ path: 'erp/siber-guvenlik/tehdit-merkezi', component: TehditMerkeziComponent },
	{ path: 'erp/siber-guvenlik/guvenlik-olaylari', component: GuvenlikOlaylariComponent },
	{ path: 'erp/dijital-iletisim/isbirligi-araclari', component: IsbirligiAraclariComponent },
	{ path: 'erp/dijital-iletisim/video-konferans', component: VideoKonferansComponent },
	{ path: 'erp/akilli-enerji/enerji-panel', component: EnerjiPanelComponent },
	{ path: 'erp/akilli-enerji/sari-yonetimi', component: SariYonetimiComponent },
	{ path: 'erp/gumruk/gumruk-beyan', component: GumrukBeyanComponent },
	{ path: 'erp/gumruk/ithalat-ihracat', component: IthalatIhracatComponent },
	{ path: 'erp/ai-musteri/chatbot-musteri', component: ChatbotMusteriComponent },
	{ path: 'erp/ai-musteri/duygu-analizi', component: DuyguAnaliziComponent },
	{ path: 'erp/dijital-saglik/saglik-takip', component: SaglikTakipComponent },
	{ path: 'erp/dijital-saglik/wellbeing-programi', component: WellbeingProgramiComponent },
	{ path: 'erp/tarim-erp/tarim-arazi', component: TarimAraziComponent },
	{ path: 'erp/tarim-erp/hasat-planlama', component: HasatPlanlamaComponent },
	{ path: 'erp/akilli-sehir/sehir-hizmetleri', component: SehirHizmetleriComponent },
	{ path: 'erp/akilli-sehir/altyapi-yonetimi', component: AltyapiYonetimiComponent },
	{ path: 'erp/fintech/kripto-fintech', component: KriptoFintechComponent },
	{ path: 'erp/fintech/mikro-finans', component: MikroFinansComponent },
	{ path: 'erp/kultur-sanat/etkinlik-yonetimi', component: EtkinlikYonetimiComponent },
	{ path: 'erp/kultur-sanat/koleksiyon-yonetimi', component: KoleksiyonYonetimiComponent },
	{ path: 'erp/spor-fitness/uye-fitness', component: UyeFitnessComponent },
	{ path: 'erp/spor-fitness/antreyman-plani', component: AntreymanPlaniComponent },
	{ path: 'erp/turizm/rezervasyon', component: RezervasyonComponent },
	{ path: 'erp/turizm/oda-yonetimi', component: OdaYonetimiComponent },
	{ path: 'erp/havacilik/ucus-yonetimi', component: UcusYonetimiComponent },
	{ path: 'erp/havacilik/bakim-planlama', component: BakimPlanlamaHavacComponent },
	{ path: 'erp/arsa-tarla/arsa-takip', component: ArsaTakipComponent },
	{ path: 'erp/arsa-tarla/tapu-islemleri', component: TapuIslemleriComponent },
	{ path: 'erp/demirbaslar/demirbaslar', component: DemirbaslarComponent },
	{ path: 'erp/demirbaslar/zimmet', component: ZimmetComponent },
	{ path: 'erp/demirbaslar/amortisman', component: AmortismanComponent },
	{ path: 'erp/hayvancilik/hayvan-takip', component: HayvanTakipComponent },
	{ path: 'erp/hayvancilik/yem-yonetimi', component: YemYonetimiComponent },
	{ path: 'erp/hayvancilik/saglik-asi', component: SaglikAsiComponent },
	{ path: '**', redirectTo: 'dashboard' }
];
